# Generated by Django 2.0.3 on 2018-04-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='url',
        ),
        migrations.AddField(
            model_name='submenu',
            name='bannerImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
